// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbZcjaAVraSdB5PSE16I3KteMtvH67no4',
    appId: '1:532533533988:web:035a0ceff5b312c89527b1',
    messagingSenderId: '532533533988',
    projectId: 'todo-17826',
    authDomain: 'todo-17826.firebaseapp.com',
    storageBucket: 'todo-17826.appspot.com',
    measurementId: 'G-Y1Q8YNWSTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn1XzYzRrIPnHS1_tQiMlOkYBToUF1vC4',
    appId: '1:532533533988:android:bdf98c31a792159c9527b1',
    messagingSenderId: '532533533988',
    projectId: 'todo-17826',
    storageBucket: 'todo-17826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC85laL92mQJOA_XD11S_8oh4Ciej6opWI',
    appId: '1:532533533988:ios:03f7b32a66036baa9527b1',
    messagingSenderId: '532533533988',
    projectId: 'todo-17826',
    storageBucket: 'todo-17826.appspot.com',
    iosClientId: '532533533988-pii30loa9fi238pvodr2g97ajhle27q9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRoute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC85laL92mQJOA_XD11S_8oh4Ciej6opWI',
    appId: '1:532533533988:ios:e9ae506822cd8a039527b1',
    messagingSenderId: '532533533988',
    projectId: 'todo-17826',
    storageBucket: 'todo-17826.appspot.com',
    iosClientId: '532533533988-kejod37mu9cjov636ut8uos6pc4skmeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoRoute.RunnerTests',
  );
}
